### PR TITLE
Add footer with links

### LINKED ISSUE #27: Properly attribute used graphics
Big pictures all come from here https://icons8.com/ouch/style/hugo-1
I'm not sure about the small ones (the ones visible in lobby)

### PR DESCRIPTION
**Pull request by pastDexter**
Closes #27 

Add footer with link to `Icons8` as described in images license

image

### CODE REVIEW

**Comment by Bombasarkadian** [comment]
That's a huge footer 👀 Can we maybe make it a little bit more discreet?

**Comment by turbaszek** [comment]
Can we use plain text? Those buttons get to much attention. Also maybe it’s good idea to have the right-upper-corner GitHub fork me?

**Comment by pastDexter** [comment]
@Bombasarkadian it's white so it looks like it's big on github as the text background is also white 😄

But yes, I can try to make it more subtle

**Comment by pastDexter** [comment]
@turbaszek I don't think we need to focus on encouraging people to fork this project 🤔

**Comment by pastDexter** [comment]
image

**Comment by Bombasarkadian** [comment]
> Can we use plain text? Those buttons get to much attention.

I agree with this. Leave buttons in the UI and make footer a simple box of text with links

**Comment by pastDexter** [comment]
image

**Pull request merged**
