### PR TITLE
Add Github Actions CI

### PR DESCRIPTION
**Pull request by turbaszek**
In this way the master branch should always be a working :)

### CODE REVIEW

**Comment by Bombasarkadian** [comment]
Why is there no "passed" badge in the readme? 😛

**Comment by turbaszek** [comment]
> Why is there no "passed" badge in the readme? 😛

The crucial part of CI 😅

**Comment by pastDexter** [comment]
Maybe we can add linter on CI?

**Comment by turbaszek** [comment]
> Maybe we can add linter on CI?

@pastDexter will do in next step. We should decide what we would like to use PTAL #24

**Comment by pastDexter** [comment]
@turbaszek @Bombasarkadian I've added separate deployment workflow that deploys server to Heroku and runs only on `master`

**Pull request merged**
